export const env = {
  NEXT_PUBLIC_TMDB_ACCESS_TOKEN: process.env.NEXT_PUBLIC_TMDB_ACCESS_TOKEN || "",
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL || "",
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "",
  NEXT_PUBLIC_CAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_CAPTCHA_SITE_KEY || "",
  NEXT_PUBLIC_AVATAR_PROVIDER_URL: process.env.NEXT_PUBLIC_AVATAR_PROVIDER_URL || "",
  NEXT_PUBLIC_MYANIMELIST_CLIENT_ID: process.env.NEXT_PUBLIC_MYANIMELIST_CLIENT_ID || "",
  NEXT_PUBLIC_MYANIMELIST_CLIENT_SECRET: process.env.NEXT_PUBLIC_MYANIMELIST_CLIENT_SECRET || "",
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY || "",
  PROTECTED_PATHS: process.env.PROTECTED_PATHS || "",
};
